---
title: "Stat 243 -- QuickCheck"
author: "Richmond Yevudza"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  html_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE, message=FALSE}
# load packages that are going to be used
require(mosaic)      # this loads ggformula (for plotting), etc. too
require(Lock5withR)  # this loads data sets from our book

# Some customization. You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw())     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small")   # slightly smaller font for code
```

<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->

### 1
```{r}
  gf_point(Price ~ PPM, data = InkjetPrinters) %>% gf_lm()
```

### 2
```{r}
  lm(Price ~ PPM, data = InkjetPrinters)
```

Equation =>  y = 90.88x - 94.22

### 3
```{r}
  lmResult <- lm(formula = Price ~ PPM, data = InkjetPrinters)
  gf_point(lmResult$residuals ~lmResult$fitted)
  gf_qq(~lmResult$residuals)
```

### 4
```{r}
  summary(lm(Price ~ PPM, data = InkjetPrinters))
```

### 5
```{r}
  summary(lm(Price ~ PPM, data = InkjetPrinters))
```

### 6
```{r}
  nrow(InkjetPrinters)
  tstar <- qt(0.96, df=18)
  lm(Price ~ PPM, data = InkjetPrinters)$coefficients[2] + c(-1,1) * tstar * 19.49
```