---
title: "Stat 243 -- Gradescope 06"
author: "Richmond Yevudza"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE, message=FALSE}
# load packages that are going to be used
require(mosaic)      # this loads ggformula (for plotting), etc. too
require(Lock5withR)  # this loads data sets from our book

# Some customization. You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw())     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small")   # slightly smaller font for code
```

<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->


### 9.10

alpha = 0.05 with n - 2 = 30 - 2 = 28 = df

t* is 2.048

CI: (-0.7670, 0.0550)


### 9.14

{r echo =TRUE}
varR <- -0.41
varN <- 18

(varR*sqrt(varN-2))/(sqrt(1-varR^2))


### 9.16

a.) Points and steals have the highest positive correlation which is 0.453. 
The p-value is 0, and the positive correlation here means that an 
increase in points or steals leads to an increase in the other value, and a 
decrease in the number of points or steals will lead to a decrease in the other value.


b.) The free throw shooting percentage and the number of rebounds mostly negatively correlated, with a value of -0.384 and a p-value of 0. 
The negative correlation here means that the higher the percentage of free 
throws, the lower the number of rebounds, and the lower the percentage of free 
throws, the higher the number of rebounds.



c.) Total list of p-values greater than 0.05:

Age/Points

FTPct/Age

Rebounds/Age

Steals/Age

Steals/FTPct

Steals/Rebounds


### 9.18

a.) No

b.) Correlation = 0.740; p-value = 0; reject the null hypothesis.

c.) BMGain = 1.11 + 0.127DayPct = 1.11 + 0.127(56) = 8.222 grams.

d.) 0.127, gives the strength of linear association between the two variables.

e.) p-value of the slope is 0, so reject the null hypothesis.

f.) They are the same.

g.) $R^2$ = 54.7%

h.) 
{r correlationSquared, include=TRUE}
0.740^2


### 9.20

a.) slope = 82.45, SE = 27.58

b.) t = 2.990

There is correlation between the normalized z-scores of grey 
matter density in certain regions and the number of friends on Facebook.

p-value = 0.005

Therefore, reject the null hypothesis.

c.) n = 40

df = 40 - 2 = 38

t critical (95% confidence): 2.024

95% CI = (82.45 - (2.024 * 27.58), 82.45 + (2.024 * 27.58))

= (26.63, 138.27)


### 9.23

a.) $R^2$

b.) prevalence of the virus; explanatory: precipitation level

c.) 0.889


### 9.28

F: 1.75

p-value: 0.187

Therefore, model isn't effective because the P-value is greater than 0.05


### 9.34

n = 361

$R^2$ = 0.02975085


### 9.41

F = 7.44

p-value = 0.011

Therefore, the model is effective because the P-value is less than 0.05


### 9.43

a.)GPA = 3.07

b.) n = 345

c.) $R^2$ = 12.5%

d.) F = 48.84; p-value = 0; the model is effective

### 9.52

a.) fitted regression: beds = 2.358512493 + 0.339337594 baths

substituting 3 into the equation:

beds (predicted in a house with 3 bathrooms) = 3.4

b.) t-stat: 1.978

p-value = 0.058 (which is greater than 0.05)

Therefore, fail to reject the null hypothesis.

c.) F-stat: 3.91

p-value: 0.058

Therefore, fail to reject the null hypothesis.

d.) $R^2$ = 12.3% 


### 9.62

a.) 143.35, 172.42 

b.) 101.46, 214.31


### 9.63

a.) p-value ≈ 0; effective predictor

b.) $571,910

c.) (445.3, 698.6) in $1000s

d.) (−133.2, 1277.0) in $1000s


### 9.66

a.) 95% CI = 5.3 ± (2.262 * 1.87)

= (1.08, 9.52)

b.) 95% PI = 5.3 ± (2.262 * 6.24)

= (-8.81, 19.41)

