---
title: "Stat 243 -- Homework 00"
author: "Richmond Yevudza"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE, message=FALSE}
# load packages that are going to be used
require(mosaic)      # this loads ggformula (for plotting), etc. too
require(Lock5withR)  # this loads data sets from our book

theme_set(theme_bw())     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small")   # slightly smaller font for code
```

<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->

### Identify different sets of value
* Categorical variable: sex
* Discrete quantitative variable: numchildren 
* Continuous quantitative variable: gpa


### Command, displaying both the command and its results
```{r}
# import the .csv data set and store it in teachingData.
teachingData <- read.csv("https://scofield.site/teaching/data/csv/ssurv.csv")

# show only cases where smoker displays smoke and specified variables of these cases.
subset(filter((teachingData), smoker == "Smoke"), select = c(sex, numchildren, gpa))
```


### Formula for sample standard deviation
s $= \sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \overline x)^2}$
